### ISSUE TITLE
make flake8 on Travis PR diff aware, and change line length

### ISSUE THREAD

**Issue by adrinjalali** [IBM/AIF360#56]
Right now, the `.travis.cli` checks for some `flake8` errors with giving out warnings, with this line:

```
# exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```

I know github's editor's max line is 127, but that's far too long for easily reviewing PRs on different systems and screens. I think it may make more sense to change that to 80 (what PEP8 recommends, with convincing arguments), and since we don't want to have to fix what already is in the repo, we can try and enforce that on new code.

`scikit-learn` for instance, uses a nice script which only fails only if there are new `flake8` warnings introduced, which can be found here: https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/flake8_diff.sh

**Comment by hoffmansc** [comment]
This seems reasonable to me. Would you be interested in putting in a PR for this?

We'll probably need to update the contributing guidelines at some point as well to reflect the style requirements.

**Comment by adrinjalali** [comment]
In the mean time, we moved the flake8 check to circle-ci (which also generates the documentations), since it's gives the feedback on flake8 issues much faster than the travis, and the developer doesn't have to wait until the whole travis job is finished. It's this one:

```
  lint:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: ./build_tools/circle/checkout_merge_commit.sh
      - run:
          name: dependencies
          command: sudo pip install flake8
      - run:
          name: flake8
command: ./build_tools/circle/flake8_diff.sh
```
Should we start configuring a circle-ci since it's also related to #57? The flake8 check would be an easy start.

I can send a PR in either case, but I think starting it on the circle-ci would be a better option.
